spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/vango
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true